- defaultTab: nodes
  description: |-
        Daily pipeline for Real State segmented traffic and content metrics
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/re_segmented_metrics:fix_re_segmented \
                        -email_from="noreply@yapo.cl" \
                        -email_to="data_team@adevinta.com"
  executionEnabled: true
  group: DOCKER/INSIGHT
  loglevel: DEBUG
  name: INSIGHT - RE Segmented Metrics
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/re_segmented_metrics:fix_re_segmented
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/re_segmented_metrics:fix_re_segmented \
                        -email_from="noreply@yapo.cl" \
                        -email_to="data_team@adevinta.com"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago