- defaultTab: nodes
  description: |-
        API Real Estate daily data collection pipeline
        sudo docker run --rm --net=host \
                    -v /home/bnbiuser/secrets/bigquery_prod_gcp:/app/gbq-secret \
                    -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                    -v /home/bnbiuser/secrets/smtp:/app/smtp-secret \
                    -e APP_GBQ_SECRET=/app/gbq-secret \
                    -e APP_DB_SECRET=/app/db-secret \
                    gcr.io/yapo-dat-prd/legacy/re-api-daily-process:latest \
                    -email_from="noreply@yapo.cl -- if put this options replace default email from" \
                    -email_to="email 1 to send data -- if put this options replace default emails to" \
                    -email_to="email n to send data"
  executionEnabled: true
  group: DOCKER/INSIGHT
  loglevel: DEBUG
  # name: INSIGHT - Insights API Real Estate daily data collection
  name : INSIGHT - Insights API Real Estate daily data V2 GCP BigQuery version
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        docker pull gcr.io/yapo-dat-prd/legacy/re-api-daily-process:latest
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/bigquery_prod_gcp:/app/gbq-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/smtp:/app/smtp-secret \
                        -e APP_GBQ_SECRET=/app/gbq-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        gcr.io/yapo-dat-prd/legacy/re-api-daily-process:latest \
                        -email_from="noreply@yapo.cl" \
                        -email_to="gp_data_analytics@yapo.cl"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
